// TODO: Clean up color codes. Don't use rgb values like this
export const LIGHT_THEME = {
  displayName: "AgentControlLightTheme",
  fragments: { edit: "rgb(42, 161, 152)" },
  styles: {
    container: {
      backgroundColor: "#f6f6f6",
      fontFamily: "monospace",
    },
    collection: {},
    collectionInner: {},
    collectionElement: {},
    dropZone: {},
    property: "#c026d3",
    bracket: { color: "#4f46e5", fontWeight: "medium" },
    itemCount: { color: "rgba(0, 0, 0, 0.3)", fontStyle: "italic" },
    string: "#4f46e5",
    number: "rgb(38, 139, 210)",
    boolean: "green",
    null: {
      color: "rgb(220, 50, 47)",
      fontVariant: "small-caps",
      fontWeight: "bold",
    },
    input: ["#292929", { fontSize: "90%" }],
    inputHighlight: "#b3d8ff",
    error: { fontSize: "0.8em", color: "red", fontWeight: "bold" },
    iconCollection: "rgb(0, 43, 54)",
    iconEdit: "edit",
    iconDelete: "rgb(203, 75, 22)",
    iconAdd: "edit",
    iconCopy: "rgb(38, 139, 210)",
    iconOk: "green",
    iconCancel: "rgb(203, 75, 22)",
  },
};

export const DARK_THEME = {
  displayName: "AgentControlDarkTheme",
  fragments: { edit: "rgb(42, 161, 152)" },
  styles: {
    container: {
      backgroundColor: "#1A1B1E",
      fontFamily: "monospace",
      color: "#C1C2C5",
    },
    collection: {},
    collectionInner: {},
    collectionElement: {},
    dropZone: {},
    property: "#e879f9",
    bracket: { color: "#818cf8", fontWeight: "medium" },
    itemCount: { color: "rgba(255, 255, 255, 0.3)", fontStyle: "italic" },
    string: "#818cf8",
    number: "rgb(102, 187, 255)",
    boolean: "#5eead4",
    null: {
      color: "rgb(239, 68, 68)",
      fontVariant: "small-caps",
      fontWeight: "bold",
    },
    input: ["#C1C2C5", { fontSize: "90%" }],
    inputHighlight: "#364fc7",
    error: { fontSize: "0.8em", color: "#f87171", fontWeight: "bold" },
    iconCollection: "rgb(193, 194, 197)",
    iconEdit: "edit",
    iconDelete: "rgb(239, 68, 68)",
    iconAdd: "edit",
    iconCopy: "rgb(102, 187, 255)",
    iconOk: "#5eead4",
    iconCancel: "rgb(239, 68, 68)",
  },
};
