"""Agent Control Models - Shared data models for server and SDK."""

from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("agent-control-models")
except PackageNotFoundError:
    __version__ = "0.0.0.dev"

from .actions import (
    ActionDecision,
    expand_action_filter,
    normalize_action,
    normalize_action_list,
)
from .agent import (
    BUILTIN_STEP_TYPES,
    STEP_TYPE_LLM,
    STEP_TYPE_TOOL,
    Agent,
    JSONObject,
    JSONValue,
    Step,
    StepSchema,
)
from .controls import (
    BooleanTemplateParameter,
    ConditionNode,
    ControlAction,
    ControlDefinition,
    ControlDefinitionRuntime,
    ControlMatch,
    ControlScope,
    ControlSelector,
    EnumTemplateParameter,
    EvaluatorResult,
    EvaluatorSpec,
    JsonValue,
    RegexTemplateParameter,
    SteeringContext,
    StringListTemplateParameter,
    StringTemplateParameter,
    TemplateControlInput,
    TemplateDefinition,
    TemplateParameterBase,
    TemplateParameterDefinition,
    TemplateValue,
    UnrenderedTemplateControl,
)
from .errors import (
    ERROR_TITLES,
    ErrorCode,
    ErrorDetails,
    ErrorMetadata,
    ErrorReason,
    ProblemDetail,
    ValidationErrorItem,
    get_error_title,
    make_error_type,
)
from .evaluation import (
    EvaluationRequest,
    EvaluationResponse,
    EvaluationResult,
)
from .health import HealthResponse
from .observability import (
    BatchEventsRequest,
    BatchEventsResponse,
    ControlExecutionEvent,
    ControlStats,
    ControlStatsResponse,
    EventQueryRequest,
    EventQueryResponse,
    StatsRequest,
    StatsResponse,
    StatsTotals,
    TimeseriesBucket,
)
from .policy import Policy
from .server import (
    AgentRef,
    AgentSummary,
    ConflictMode,
    ControlSummary,
    DeleteControlResponse,
    EvaluatorSchema,
    GetPolicyControlsResponse,
    InitAgentEvaluatorRemoval,
    InitAgentOverwriteChanges,
    ListAgentsResponse,
    ListControlsResponse,
    PaginationInfo,
    PatchControlRequest,
    PatchControlResponse,
    RenderControlTemplateRequest,
    RenderControlTemplateResponse,
    StepKey,
    ValidateControlDataRequest,
    ValidateControlDataResponse,
)

__all__ = [
    # Health
    "HealthResponse",
    # Agent
    "Agent",
    "StepSchema",
    "JSONValue",
    "JSONObject",
    "Step",
    "STEP_TYPE_TOOL",
    "STEP_TYPE_LLM",
    "BUILTIN_STEP_TYPES",
    "ActionDecision",
    # Policy
    "Policy",
    # Evaluation
    "EvaluationRequest",
    "EvaluationResponse",
    "EvaluationResult",
    # Controls
    "ControlDefinition",
    "ConditionNode",
    "ControlAction",
    "ControlMatch",
    "ControlScope",
    "ControlSelector",
    "ControlDefinitionRuntime",
    "EvaluatorSpec",
    "EvaluatorResult",
    "SteeringContext",
    "JsonValue",
    "TemplateValue",
    "TemplateParameterBase",
    "StringTemplateParameter",
    "StringListTemplateParameter",
    "EnumTemplateParameter",
    "BooleanTemplateParameter",
    "RegexTemplateParameter",
    "TemplateParameterDefinition",
    "TemplateDefinition",
    "TemplateControlInput",
    "UnrenderedTemplateControl",
    "normalize_action",
    "normalize_action_list",
    "expand_action_filter",
    # Error models
    "ProblemDetail",
    "ErrorCode",
    "ErrorReason",
    "ErrorDetails",
    "ErrorMetadata",
    "ValidationErrorItem",
    "make_error_type",
    "get_error_title",
    "ERROR_TITLES",
    # Server models
    "AgentRef",
    "AgentSummary",
    "ConflictMode",
    "ControlSummary",
    "DeleteControlResponse",
    "EvaluatorSchema",
    "GetPolicyControlsResponse",
    "InitAgentEvaluatorRemoval",
    "InitAgentOverwriteChanges",
    "ListAgentsResponse",
    "ListControlsResponse",
    "PaginationInfo",
    "PatchControlRequest",
    "PatchControlResponse",
    "RenderControlTemplateRequest",
    "RenderControlTemplateResponse",
    "StepKey",
    "ValidateControlDataRequest",
    "ValidateControlDataResponse",
    # Observability models
    "ControlExecutionEvent",
    "BatchEventsRequest",
    "BatchEventsResponse",
    "EventQueryRequest",
    "EventQueryResponse",
    "ControlStats",
    "ControlStatsResponse",
    "StatsRequest",
    "StatsResponse",
    "StatsTotals",
    "TimeseriesBucket",
]
