"""
Revision ID: 58920e6807fe
Revises: d2f4a6b8c9d0
Create Date: 2026-02-25 17:56:34.057000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58920e6807fe'
down_revision = '53d8427083e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agents_name_key'), 'agents', type_='unique')
    op.drop_column('agents', 'agent_uuid')
    op.create_primary_key('agents_pkey', 'agents', ['name'])
    op.create_check_constraint('ck_agents_name_min_length', 'agents', 'char_length(name) >= 10')
    op.create_check_constraint('ck_agents_name_format', 'agents', "name ~ '^[a-z0-9:_-]+$'")
    op.add_column('control_execution_events', sa.Column('agent_name', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_events_agent_time'), table_name='control_execution_events')
    op.create_index('ix_events_agent_time', 'control_execution_events', ['agent_name', sa.literal_column('timestamp DESC')], unique=False)
    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_events_data_control_id
        ON control_execution_events ((data ->> 'control_id'::text))
    """)
    op.drop_column('control_execution_events', 'agent_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control_execution_events', sa.Column('agent_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index('ix_events_agent_time', table_name='control_execution_events')
    op.create_index(op.f('ix_events_agent_time'), 'control_execution_events', ['agent_uuid', sa.literal_column('timestamp DESC')], unique=False)
    op.drop_column('control_execution_events', 'agent_name')
    op.drop_constraint('ck_agents_name_format', 'agents', type_='check')
    op.drop_constraint('ck_agents_name_min_length', 'agents', type_='check')
    op.drop_constraint('agents_pkey', 'agents', type_='primary')
    op.add_column('agents', sa.Column('agent_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.create_primary_key('agents_pkey', 'agents', ['agent_uuid'])
    op.create_unique_constraint(op.f('agents_name_key'), 'agents', ['name'], postgresql_nulls_not_distinct=False)
    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_events_data_control_id
        ON control_execution_events ((data ->> 'control_id'::text))
    """)
    # ### end Alembic commands ###
